### ISSUE TITLE
Aufgabe

### ISSUE THREAD

**Issue by MoritzGoeckel** [madjoel/teambuktu#1]
Habe ich es richtig verstanden, dass ich im "DataService.ts" add, update und delete Methoden schreiben soll? Also sowas wie "updateAppointment" etc?

Will nur kurz sichergehen, dass ich da jetzt nicht in eine falsche Richtung losarbeite.

**Comment by madjoel** [comment]
Macht das nicht schon Béla?

**Comment by MoritzGoeckel** [comment]
Er meinte gestern ich koennte ihm da was abnehmen

**Comment by madjoel** [comment]
Ach so - dann passt das ja. Es geht darum, dass man aus dem UI, wenn Änderungen gemacht wurden, diese durch die update- und delete-Methoden wieder in den DataService reinbekommt.
